### ISSUE TITLE
Content area in <paper-horizontal-stepper> does not grow with stepper

### ISSUE THREAD

**Issue by dantman** [Zecat/paper-stepper#14]
The `#slideshow` in `<paper-horizontal-stepper>` doesn't have a `flex` value set on it. So when you try to make the stepper taller, the content area does not grow with the stepper.

**Comment by dantman** [comment]
Additionally `<paper-stepper>` does not use flex to make sure the horizontal stepper fills the stepper it is inside of.

**Comment by Zecat** [comment]
For your second comment, I think the horizontal stepper should not fill the stepper, but on the contrary, the horizontal stepper should stretch the stepper because usually, you don't want to define a height for paper-stepper when using vertical layout and you may want to pass from horizontal to vertical layout (based on media-query for example). So a CSS variable `paper-horizontal-stepper-height` would be appropriate in `<paper-stepper>`. Also, in addition to the `flex` value, we should remove `min-height: 200px;` for the `#slideshow` and instead give a default height to the horizontal stepper, 450px maybe ?

**Comment by dantman** [comment]
By filling the stepper, I'm referring to how if you do chose to set a height on the paper-stepper, it won't affect the horizontal stepper, which will remain a height based on the 200px.
![screen shot 2016-06-15 at 10 24 49 pm](https://cloud.githubusercontent.com/assets/53399/16106337/6bc808ce-3348-11e6-8fae-6eb64cd54eb4.png)

This affects me because my paper-stepper is the only entity in a full-page desktop layout, so I want the stepper to fill the page and apply flex to it.

**Comment by hubgit** [comment]
I was able to push a horizontal stepper and its steps to take up the full height by adding these styles (which quite possibly break things for vertical steps):

``` diff
diff -u ../master/paper-stepper/paper-horizontal-stepper.html ./paper-horizontal-stepper.html
--- ../master/paper-stepper/paper-horizontal-stepper.html  2016-08-09 14:03:36.000000000 +0100
+++ ./paper-horizontal-stepper.html 2016-08-09 14:01:48.000000000 +0100
@@ -27,6 +27,7 @@
         display: block;
         box-sizing: border-box;
         @apply(--layout-vertical);
+        @apply(--layout-flex);
       }
       #stepSelector {
         @apply(--shadow-elevation-2dp);
@@ -38,6 +39,7 @@
       }
       neon-animated-pages {
         @apply(--layout-vertical);
+        @apply(--layout-flex);
         min-height: 200px;
       }
       #buttonsWrapper {
diff -u ../master/paper-stepper/paper-step.html ./paper-step.html
--- ../master/paper-stepper/paper-step.html  2016-08-09 14:03:36.000000000 +0100
+++ ./paper-step.html 2016-08-09 13:56:32.000000000 +0100
@@ -12,6 +12,8 @@
       :host {
         display: block;
         box-sizing: border-box;
+        @apply(--layout-scroll);
+        @apply(--layout-flex);
       }
     </style>
     <content></content>
diff -u ../master/paper-stepper/paper-stepper.html ./paper-stepper.html
--- ../master/paper-stepper/paper-stepper.html 2016-08-09 14:03:36.000000000 +0100
+++ ./paper-stepper.html  2016-08-09 14:00:15.000000000 +0100
@@ -21,6 +21,8 @@
       :host {
         display: block;
         box-sizing: border-box;
+        @apply(--layout-flex);
+        @apply(--layout-vertical);
       }
```
