### ISSUE TITLE
add horizontal layout

### ISSUE THREAD

**Issue by Zecat** [Zecat/paper-stepper#2]

**Comment by mathieumante** [comment]
+1 !

**Comment by dominikIncibit** [comment]
+2

**Comment by patgmiller** [comment]
@mathieumante and @fleckdalm, since progress seems to have halted here I started my own implementation of Material Design steppers, [paper-steps](https://github.com/patgmiller/paper-steps), which has the horizontal feature. Feel free to give it a try and offer any feed back.
