### ISSUE TITLE
In with 2.0-beta.2 paper-stepper rendering issue

### ISSUE THREAD

**Issue by sowsan** [Zecat/paper-stepper#39]
2nd step always overlapping with the 3rd step.

![image](https://cloud.githubusercontent.com/assets/11544153/17492361/7558f244-5d79-11e6-802d-f1623ae10d42.png)

**Comment by Zecat** [comment]
Thanks, I forgot to manage `iron-collapse` overflow, it should be fixed in beta.3 can you confirm?

**Comment by sowsan** [comment]
Great, Tried it in beta.3 and its fixed. Awesome job. Thank you @Zecat
