### ISSUE TITLE
Allow a completed step to be re-opened for editing

### ISSUE THREAD

**Issue by hubgit** [Zecat/paper-stepper#43]
If a step has been completed using the Continue button, the step heading is marked with a check and can no longer be opened for editing.

I'd like to allow users to open a previous step for editing again, by clicking on the heading.

![screen shot 2016-08-09 at 10 55 38](https://cloud.githubusercontent.com/assets/14294/17512487/f43c8eda-5e1f-11e6-94d9-8bdd1950c528.png)

(2.0-beta.3)

**Comment by Zecat** [comment]
Just add "editable" attribute to the `<paper-step>` you want to be editable! Sorry there is no doc for the moment I'll work on that soon!

**Comment by hubgit** [comment]
Perfect - thanks!
