### ISSUE TITLE
paper-step: unroll-animation not found!

### ISSUE THREAD

**Issue by bradleyjkemp** [Zecat/paper-stepper#55]
I'm trying to use the demo vertical stepper but I get the error "paper-step: unroll-animation not found!" in the console and the stepper isn't styled (although does function).

I tried changing the animationConfig to use different animations (e.g. ones from neon-animation rather than from neon-advanced-animations) but these didn't work either (the animation still couldn't be found).

Any ideas? I'm thinking its something I'm not doing right like not including the right file in order to get the animations.

**Comment by Zecat** [comment]
The last release "2.0-beta.4" isn't using unroll-animation anymore, update your dependency and it should be fine ;)
