### ISSUE TITLE
Not displaying correctly

### ISSUE THREAD

**Issue by harso121** [Zecat/paper-stepper#57]
![err](https://cloud.githubusercontent.com/assets/14226197/21156953/f34c611a-c177-11e6-8e3e-1df0d41a7dc8.PNG)

I imported "paper-stepper/paper-stepper.html" correctly as well as "paper-stepper/paper-step" (if I don't import "paper-step" as well I get "paper-stepper.html:127 Uncaught TypeError: e.detail.item.open is not a function" as error)

But it just doesn't seem to be right, it's also always vertical, no matter what I add.

**Comment by Zecat** [comment]
Hi, I think you are using the 1.0 version, try `bower install -S Zecat/paper-stepper#v2.0-beta.4` for now, I'll try to make a 2.0 stable release for next week.

**Comment by harso121** [comment]
Thanks, that did it! :)
